---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      apt:
        name: 
          - postgresql
          - postgresql-server
        state: present

    - name: "Install Python packages"
      pip: 
        name: 
          - psycopg2-binary
        state: present

  tasks:
    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service:
        name: postgresql 
        state: started 
        enabled: yes

  handlers:
    - name: restart postgres
      service: 
        name: postgresql 
        state: restarted