---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf:
        state: present
        name: 
          - postgresql
          - postgresql-server

    # - name: "Install Python packages"
    #   yum: 
    #     name: python3-psycopg2
    #     state: present

  # tasks:
  #   - name: "Initialize PostgreSQL"
  #     shell: "postgresql-setup initdb"
  #     when: not postgres_data.stat.exists

    # - name: "Start and enable services"
    #   service:
    #     name: postgresql 
    #     state: started 
    #     enabled: yes

  # handlers:
  #   - name: restart postgres
  #     service: 
  #       name: postgresql 
  #       state: restarted